In [2]:
import os 
import pandas as pd 
import numpy as np

from dotenv import load_dotenv

import requests 
import json

TO DO:

- get list of air quality sensors (Golemio)
- get list of microclimate sensors (Golemio)
- get list of Weather stations (CHMI)

- join this to one dataset mapping the relevent locations together

- download relevant datasources, joint them based on mapping defined above 

- do analysis (...)

In [ ]:
#data chmi

#https://opendata.chmi.cz/meteorology/climate/historical/data/1hour/

#kbely wsi 0-20000-0-11567

## this gets ony one specific station !!!

In [20]:
chmi_url = 'https://opendata.chmi.cz/'
chmi_route = '/meteorology/climate/historical/data/1hour/2020/1h-0-20000-0-11567-202003.json'

chmi_headers = {
    'accept': 'application/json',
    'User-Agent': 'JEM207 DataProcessingCourse (Educational access; contact: 19658413@fsv.cuni.cz)'
}

chmi_params = { 
            'from': '2020-03-13T10:54:00.000Z', 
            'to': '2020-03-15T13:05:00.000Z'
}

chmi_response = requests.get(f'{chmi_url}{chmi_route}', headers = chmi_headers, timeout = 60)

data_chmi = chmi_response.json()

In [21]:
print(type(data_chmi))
print(data_chmi.keys())
print(data_chmi['data'].keys())
print(data_chmi['data']['data'].keys())

print(data_chmi)

<class 'dict'>
dict_keys(['zaznamID', 'datovyZdrojID', 'datovyTokID', 'datumVytvoreni', 'verzeDat', 'data'])
dict_keys(['type', 'data'])
dict_keys(['header', 'values'])

In [22]:
data_chmi_sub = data_chmi['data']['data']
chmi_headers = data_chmi_sub['header'].split(',')
chmi_values = data_chmi_sub['values']

df_chmi = pd.DataFrame(chmi_values, columns=chmi_headers)

df_chmi.head()

           STATION ELEMENT                    DT  VAL FLAG  QUALITY
0  0-20000-0-11567       E  2020-03-01T00:00:00Z  7.3           0.0
1  0-20000-0-11567       E  2020-03-01T01:00:00Z  8.2           0.0
2  0-20000-0-11567       E  2020-03-01T02:00:00Z  8.3           0.0
3  0-20000-0-11567       E  2020-03-01T03:00:00Z  7.7           0.0
4  0-20000-0-11567       E  2020-03-01T04:00:00Z  7.6           0.0

In [ ]:
### golemio data 


##### air quality

## metadata: https://opendata.chmi.cz//air_quality/recent/metadata/metadata.json

In [3]:
load_dotenv('api_key.env')
api_key = os.getenv('GOLEMIO_API_KEY')

print(api_key is not None)

True

In [4]:
api_url = 'https://api.golemio.cz/'
route = '/v2/airqualitystations'

headers = {
    'X-access-token': api_key, 
    'accept': 'application/json',
    'User-Agent': 'JEM207 DataProcessingCourse (Educational access; contact: 19658413@fsv.cuni.cz)'
}

params = {

}

response = requests.get(f'{api_url}{route}', headers = headers, timeout = 60)

data = response.json()

In [5]:
print(type(data))

print(data.keys())

<class 'dict'>
dict_keys(['features', 'type'])

In [6]:
print(json.dumps(data, indent=2, ensure_ascii = False))

{
  "features": [
    {
      "geometry": {
        "coordinates": [
          14.380116,
          50.084385
        ],
        "type": "Point"
      },
      "properties": {
        "measurement": {
          "AQ_hourly_index": "1B",
          "components": [
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 36.3
              },
              "type": "NO2"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 30.5
              },
              "type": "PM10"
            }
          ]
        },
        "id": "ABREA",
        "name": "Praha 6-Břevnov",
        "updated_at": "2026-04-27T08:40:00.896Z",
        "district": "praha-6"
      },
      "type": "Feature"
    },
    {
      "geometry": {
        "coordinates": [
          14.44365,
          50.108845
        ],
        "type": "Point"
      },
      "properties": {
        "measurement": {
          "AQ_hourly_index": "1B",
          "components": [
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 42
              },
              "type": "NO2"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 38.7
              },
              "type": "PM10"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 23
              },
              "type": "PM2_5"
            }
          ]
        },
        "id": "AHOLA",
        "name": "Praha 7-Holešovice",
        "updated_at": "2026-04-27T08:40:00.896Z",
        "district": "praha-7"
      },
      "type": "Feature"
    },
    {
      "geometry": {
        "coordinates": [
          14.51745,
          50.03017
        ],
        "type": "Point"
      },
      "properties": {
        "measurement": {
          "AQ_hourly_index": "1B",
          "components": [
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 37.4
              },
              "type": "NO2"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 27.3
              },
              "type": "PM10"
            }
          ]
        },
        "id": "ACHOA",
        "name": "Praha 4-Chodov",
        "updated_at": "2026-04-27T08:40:00.896Z",
        "district": "praha-11"
      },
      "type": "Feature"
    },
    {
      "geometry": {
        "coordinates": [
          14.442049,
          50.094238
        ],
        "type": "Point"
      },
      "properties": {
        "measurement": {
          "AQ_hourly_index": "2A",
          "components": [
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 43.4
              },
              "type": "NO2"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 40.7
              },
              "type": "PM10"
            }
          ]
        },
        "id": "AKALA",
        "name": "Praha 8-Karlín",
        "updated_at": "2026-04-27T08:40:00.896Z",
        "district": "praha-8"
      },
      "type": "Feature"
    },
    {
      "geometry": {
        "coordinates": [
          14.467578,
          50.122189
        ],
        "type": "Point"
      },
      "properties": {
        "measurement": {
          "AQ_hourly_index": "1B",
          "components": [
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 45.1
              },
              "type": "NO2"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 20.5
              },
              "type": "O3"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 27.9
              },
              "type": "PM10"
            }
          ]
        },
        "id": "AKOBA",
        "name": "Praha 8-Kobylisy",
        "updated_at": "2026-04-27T08:40:00.896Z",
        "district": "praha-8"
      },
      "type": "Feature"
    },
    {
      "geometry": {
        "coordinates": [
          14.430673,
          50.072388
        ],
        "type": "Point"
      },
      "properties": {
        "measurement": {
          "AQ_hourly_index": "2A",
          "components": [
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 55.6
              },
              "type": "NO2"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 39.9
              },
              "type": "PM10"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 19.7
              },
              "type": "PM2_5"
            }
          ]
        },
        "id": "ALEGA",
        "name": "Praha 2-Legerova (hot spot)",
        "updated_at": "2026-04-27T08:40:00.896Z",
        "district": "praha-2"
      },
      "type": "Feature"
    },
    {
      "geometry": {
        "coordinates": [
          14.257226,
          50.107086
        ],
        "type": "Point"
      },
      "properties": {
        "measurement": {
          "AQ_hourly_index": "1B",
          "components": [
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 20.3
              },
              "type": "NO2"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 51.7
              },
              "type": "O3"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 38.2
              },
              "type": "PM10"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 10.8
              },
              "type": "PM2_5"
            }
          ]
        },
        "id": "ALERA",
        "name": "Letiště Praha",
        "updated_at": "2026-04-27T08:40:00.896Z",
        "district": "praha-6"
      },
      "type": "Feature"
    },
    {
      "geometry": {
        "coordinates": [
          14.445933,
          50.007305
        ],
        "type": "Point"
      },
      "properties": {
        "measurement": {
          "AQ_hourly_index": "1B",
          "components": [
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 19.1
              },
              "type": "NO2"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 36.4
              },
              "type": "O3"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 30.4
              },
              "type": "PM10"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 18.8
              },
              "type": "PM2_5"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 2.4
              },
              "type": "SO2"
            }
          ]
        },
        "id": "ALIBA",
        "name": "Praha 4-Libuš",
        "updated_at": "2026-04-27T08:40:00.896Z",
        "district": "praha-12"
      },
      "type": "Feature"
    },
    {
      "geometry": {
        "coordinates": [
          14.53782,
          50.062298
        ],
        "type": "Point"
      },
      "properties": {
        "measurement": {
          "AQ_hourly_index": "2A",
          "components": [
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 53
              },
              "type": "NO2"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 51.7
              },
              "type": "PM10"
            }
          ]
        },
        "id": "APRUA",
        "name": "Praha 10-Průmyslová",
        "updated_at": "2026-04-27T08:40:00.896Z",
        "district": "praha-15"
      },
      "type": "Feature"
    },
    {
      "geometry": {
        "coordinates": [
          14.42922,
          50.088066
        ],
        "type": "Point"
      },
      "properties": {
        "measurement": {
          "AQ_hourly_index": "2A",
          "components": [
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 39.5
              },
              "type": "NO2"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 42.9
              },
              "type": "PM10"
            }
          ]
        },
        "id": "AREPA",
        "name": "Praha 1-n. Republiky",
        "updated_at": "2026-04-27T08:40:00.896Z",
        "district": "praha-1"
      },
      "type": "Feature"
    },
    {
      "geometry": {
        "coordinates": [
          14.309583,
          50.030514
        ],
        "type": "Point"
      },
      "properties": {
        "measurement": {
          "AQ_hourly_index": "1B",
          "components": [
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 32.4
              },
              "type": "NO2"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 22.3
              },
              "type": "PM10"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 8.8
              },
              "type": "PM2_5"
            }
          ]
        },
        "id": "ARERA",
        "name": "Praha 5-Řeporyje",
        "updated_at": "2026-04-27T08:40:00.896Z",
        "district": "praha-reporyje"
      },
      "type": "Feature"
    },
    {
      "geometry": {
        "coordinates": [
          14.442692,
          50.081482
        ],
        "type": "Point"
      },
      "properties": {
        "measurement": {
          "AQ_hourly_index": "1A",
          "components": [
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 1
              },
              "type": "NO2"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 20.8
              },
              "type": "O3"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 25.7
              },
              "type": "PM10"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 17.9
              },
              "type": "PM2_5"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 1.9
              },
              "type": "SO2"
            }
          ]
        },
        "id": "ARIEA",
        "name": "Praha 2-Riegrovy sady",
        "updated_at": "2026-04-27T08:40:00.896Z",
        "district": "praha-2"
      },
      "type": "Feature"
    },
    {
      "geometry": {
        "coordinates": [
          14.472661,
          50.07515
        ],
        "type": "Point"
      },
      "properties": {
        "measurement": {
          "AQ_hourly_index": "1B",
          "components": [
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 31.4
              },
              "type": "NO2"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 29.2
              },
              "type": "PM10"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 10.8
              },
              "type": "PM2_5"
            }
          ]
        },
        "id": "ASROA",
        "name": "Praha 10-Šrobárova",
        "updated_at": "2026-04-27T08:40:00.896Z",
        "district": "praha-10"
      },
      "type": "Feature"
    },
    {
      "geometry": {
        "coordinates": [
          14.331413,
          50.046131
        ],
        "type": "Point"
      },
      "properties": {
        "measurement": {
          "AQ_hourly_index": "1A",
          "components": [
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 37.1
              },
              "type": "O3"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 12.3
              },
              "type": "PM10"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 7.8
              },
              "type": "PM2_5"
            }
          ]
        },
        "id": "ASTOA",
        "name": "Praha 5-Stodůlky",
        "updated_at": "2026-04-27T08:40:00.896Z",
        "district": "praha-13"
      },
      "type": "Feature"
    },
    {
      "geometry": {
        "coordinates": [
          14.384639,
          50.12653
        ],
        "type": "Point"
      },
      "properties": {
        "measurement": {
          "AQ_hourly_index": "1A",
          "components": [
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 59.4
              },
              "type": "O3"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 19.4
              },
              "type": "PM10"
            }
          ]
        },
        "id": "ASUCA",
        "name": "Praha 6-Suchdol",
        "updated_at": "2026-04-27T08:40:00.896Z",
        "district": "praha-lysolaje"
      },
      "type": "Feature"
    },
    {
      "geometry": {
        "coordinates": [
          14.446152,
          50.066429
        ],
        "type": "Point"
      },
      "properties": {
        "measurement": {
          "AQ_hourly_index": "1B",
          "components": [
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 36.5
              },
              "type": "NO2"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 26.6
              },
              "type": "PM10"
            }
          ]
        },
        "id": "AVRSA",
        "name": "Praha 10-Vršovice",
        "updated_at": "2026-04-27T08:40:00.896Z",
        "district": "praha-10"
      },
      "type": "Feature"
    },
    {
      "geometry": {
        "coordinates": [
          14.503096,
          50.11108
        ],
        "type": "Point"
      },
      "properties": {
        "measurement": {
          "AQ_hourly_index": "2A",
          "components": [
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 47
              },
              "type": "NO2"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 14.2
              },
              "type": "O3"
            },
            {
              "averaged_time": {
                "averaged_hours": "3",
                "value": 66.8
              },
              "type": "PM10"
            }
          ]
        },
        "id": "AVYNA",
        "name": "Praha 9-Vysočany",
        "updated_at": "2026-04-27T08:40:00.896Z",
        "district": "praha-9"
      },
      "type": "Feature"
    }
  ],
  "type": "FeatureCollection"
}

In [7]:
def print_json_structure(obj, indent=0):
    pad = "  " * indent

    if isinstance(obj, dict):
        for key, value in obj.items():
            print(f"{pad}{key}: {type(value).__name__}")
            print_json_structure(value, indent + 1)

    elif isinstance(obj, list):
        print(f"{pad}[list] len={len(obj)}")
        if obj:
            print_json_structure(obj[0], indent + 1)

print_json_structure(data)

features: list
  [list] len=17
    geometry: dict
      coordinates: list
        [list] len=2
      type: str
    properties: dict
      measurement: dict
        AQ_hourly_index: str
        components: list
          [list] len=2
            averaged_time: dict
              averaged_hours: str
              value: float
            type: str
      id: str
      name: str
      updated_at: str
      district: str
    type: str
type: str

In [82]:
features = data['features']
df = pd.json_normalize(features)

In [83]:
tmp = df.explode("properties.measurement.components", ignore_index=True)
dirs = pd.json_normalize(
    tmp["properties.measurement.components"]
).add_prefix("properties.measurement.components.")

df = pd.concat([tmp.drop(columns=["properties.measurement.components"]), dirs], axis=1)

df.head()

,type,geometry.coordinates,geometry.type,properties.measurement.AQ_hourly_index,properties.id,properties.name,properties.updated_at,properties.district,properties.measurement.components.type,properties.measurement.components.averaged_time.averaged_hours,properties.measurement.components.averaged_time.value
0,Feature,"[14.380116, 50.084385]",Point,1B,ABREA,Praha 6-Břevnov,2026-04-27T08:40:00.896Z,praha-6,NO2,3,36.3
1,Feature,"[14.380116, 50.084385]",Point,1B,ABREA,Praha 6-Břevnov,2026-04-27T08:40:00.896Z,praha-6,PM10,3,30.5
2,Feature,"[14.44365, 50.108845]",Point,1B,AHOLA,Praha 7-Holešovice,2026-04-27T08:40:00.896Z,praha-7,NO2,3,42.0
3,Feature,"[14.44365, 50.108845]",Point,1B,AHOLA,Praha 7-Holešovice,2026-04-27T08:40:00.896Z,praha-7,PM10,3,38.7
4,Feature,"[14.44365, 50.108845]",Point,1B,AHOLA,Praha 7-Holešovice,2026-04-27T08:40:00.896Z,praha-7,PM2_5,3,23.0

In [84]:
station_cols = {
    'geometry.coordinates': 'coordinates', 
    'properties.id': 'id', 
    'properties.name': 'name', 
    'properties.district': 'district', 
    'properties.measurement.components.type': 'components'
}

In [85]:
air_quality_stations = df[station_cols.keys()]

air_quality_stations = air_quality_stations.rename(columns=station_cols)

In [88]:
air_quality_stations.head()

,id,coordinates,name,district,components
0,ABREA,"[14.380116, 50.084385]",Praha 6-Břevnov,praha-6,"[NO2, PM10]"
1,ACHOA,"[14.51745, 50.03017]",Praha 4-Chodov,praha-11,"[NO2, PM10]"
2,AHOLA,"[14.44365, 50.108845]",Praha 7-Holešovice,praha-7,"[NO2, PM10, PM2_5]"
3,AKALA,"[14.442049, 50.094238]",Praha 8-Karlín,praha-8,"[NO2, PM10]"
4,AKOBA,"[14.467578, 50.122189]",Praha 8-Kobylisy,praha-8,"[NO2, O3, PM10]"

In [87]:
air_quality_stations = (
    air_quality_stations.groupby('id', as_index=False)
    .agg({
        'coordinates': 'first',
        'name': 'first',
        'district': 'first',
        'components': list
    })
)

In [ ]:
#### golemio

### microclimate sensors

In [ ]:
# TODO if necessary