In [7]:
%load_ext autoreload
%autoreload 2

import sys
import os

import pandas as pd

script_folder = os.path.abspath(os.path.join('..', 'src'))

if script_folder not in sys.path:
    sys.path.append(script_folder)

import download_data as downloader

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [ ]:
#download data

In [3]:
df_weather_meta = downloader.download_chmi_weather_stations_metadata()

df_weather_meta.head()

,WSI,GH_ID,BEGIN_DATE,END_DATE,FULL_NAME,GEOGR1,GEOGR2,ELEVATION
0,0-20000-0-04030,ZIS04030,2015-01-01T00:00:00Z,3999-12-31T23:59:00Z,Reykjavik,-21.903905,64.127653,51.0
1,0-20000-0-11406,L3CHEB01,1863-10-01T00:00:00Z,1919-12-31T23:59:00Z,Cheb,12.362892,50.076212,458.0
2,0-20000-0-11406,L3CHEB01,1933-05-07T00:00:00Z,1938-04-30T23:59:00Z,Cheb,12.388900,50.0739,471.0
3,0-20000-0-11406,L3CHEB01,1943-06-01T00:00:00Z,1945-01-31T23:59:00Z,Cheb,12.388900,50.0739,471.0
4,0-20000-0-11406,L3CHEB01,1951-01-01T00:00:00Z,1960-12-31T23:59:00Z,Cheb,12.388900,50.0739,471.0

In [4]:
df_weather_stats_meta = downloader.download_chmi_weather_variables_metadata()

df_weather_stats_meta.head()

,OBS_TYPE,WSI,BEGIN_DATE,END_DATE,EG_EL_ABBREVIATION,NAME,UN_DESCRIPTION,HEIGHT,SCHEDULE
0,DLY,0-20000-0-11406,1863-10-01T00:00:00Z,1919-12-31T23:59:00Z,T,Teplota,°C,2.0,"AVG,06:00,13:00,20:00"
1,DLY,0-20000-0-11406,1865-06-01T00:00:00Z,1919-12-31T23:59:00Z,TMI,Teplota min,°C,2.0,20:00
2,DLY,0-20000-0-11406,1865-06-01T00:00:00Z,1919-12-31T23:59:00Z,TMA,Teplota max,°C,2.0,20:00
3,DLY,0-20000-0-11406,1933-05-07T00:00:00Z,1938-04-30T23:59:00Z,SSV,Sluneční svit,hod,2.0,00:00
4,DLY,0-20000-0-11406,1943-06-01T00:00:00Z,1945-01-31T23:59:00Z,SSV,Sluneční svit,hod,2.0,00:00

In [11]:
wsi_dict = downloader.build_and_save_wsi_dict()

print(f"Found {len(wsi_dict)} Prague weather stations:")
print(pd.DataFrame(list(wsi_dict.items()), columns=["key", "value"]))

Found 9 Prague weather stations:
                   key               value
0  0-203-0-10904013001     Praha, Komořany
1      0-20000-0-11567        Praha, Kbely
2  0-203-0-11201024001      Praha, Břevnov
3      0-20000-0-11520        Praha, Libuš
4      0-20000-0-11519       Praha, Karlov
5        0-203-0-11514  Praha, Klementinum
6      0-20000-0-11518       Praha, Ruzyně
7        0-203-0-11515  Praha, Klementinum
8  0-203-0-11101007001         Praha, Brdy

In [13]:
df_weather = downloader.download_chmi_weather_data()

display(df_weather.info())
display(df_weather.head())

Loaded 0-203-0-10904013001 Praha, Komořany
Loaded 0-20000-0-11567 Praha, Kbely
Loaded 0-203-0-11201024001 Praha, Břevnov
Loaded 0-20000-0-11520 Praha, Libuš
Loaded 0-20000-0-11519 Praha, Karlov
Loaded 0-203-0-11514 Praha, Klementinum
Loaded 0-20000-0-11518 Praha, Ruzyně
Loaded 0-203-0-11515 Praha, Klementinum
Loaded 0-203-0-11101007001 Praha, Brdy
<class 'pandas.DataFrame'>
RangeIndex: 5045400 entries, 0 to 5045399
Data columns (total 9 columns):
 #   Column   Dtype
---  ------   -----
 0   STATION  str
 1   ELEMENT  str
 2   DT       str
 3   VAL      object
 4   FLAG     str
 5   QUALITY  float64
 6   WSI      str
 7   YEAR     str
 8   MONTH    str
dtypes: float64(1), object(1), str(7)
memory usage: 634.7+ MB

None

,STATION,ELEMENT,DT,VAL,FLAG,QUALITY,WSI,YEAR,MONTH
0,0-203-0-10904013001,H,2025-01-01T00:00:00Z,93.0,,0.0,0-203-0-10904013001,2025,01
1,0-203-0-10904013001,H,2025-01-01T00:10:00Z,93.0,,0.0,0-203-0-10904013001,2025,01
2,0-203-0-10904013001,H,2025-01-01T00:20:00Z,93.0,,0.0,0-203-0-10904013001,2025,01
3,0-203-0-10904013001,H,2025-01-01T00:30:00Z,93.0,,0.0,0-203-0-10904013001,2025,01
4,0-203-0-10904013001,H,2025-01-01T00:40:00Z,93.0,,0.0,0-203-0-10904013001,2025,01

In [17]:
air_qual_meta = downloader.download_airquality_metadata()

air_qual_meta.head()

,id_registration,station_code,locality_code,locality_name,street,city,lon,lat,alt,component_code,component_name,unit
39,783575,AREPA,AREP,Praha 1-n. Republiky,,,14.429220,50.088066,190 m,NO2,oxid dusičitý,ug/m^3
40,783579,AREPA,AREP,Praha 1-n. Republiky,,,14.429220,50.088066,190 m,NOx,oxidy dusíku,ug/m^3
41,783591,AREPA,AREP,Praha 1-n. Republiky,,,14.429220,50.088066,190 m,PM10,částice PM10,ug/m^3
42,1648334,AREPA,AREP,Praha 1-n. Republiky,,,14.429220,50.088066,190 m,INDX,Index kvality ovzduší,
66,41157,ALEGA,ALEG,Praha 2-Legerova (hot spot),Legerov 1843,Praha 2,14.430673,50.072388,219 m,NO2,oxid dusičitý,ug/m^3

In [18]:
air_stat_dict = downloader.build_and_save_air_stations_dict()

print(f"Found {len(air_stat_dict)} Prague air stations:")
print(pd.DataFrame(list(air_stat_dict.items()), columns=["key", "value"]))

Found 14 Prague air stations:
      key                        value
0   AREPA         Praha 1-n. Republiky
1   ALEGA  Praha 2-Legerova (hot spot)
2   AKALA               Praha 8-Karlín
3   AVYNA             Praha 9-Vysočany
4   ALIBA                Praha 4-Libuš
5   ASTOA             Praha 5-Stodůlky
6   APRUA          Praha 10-Průmyslová
7   AHOLA           Praha 7-Holešovice
8   AKOBA             Praha 8-Kobylisy
9   ASUCA              Praha 6-Suchdol
10  ARIEA        Praha 2-Riegrovy sady
11  AVRSA            Praha 10-Vršovice
12  ABREA              Praha 6-Břevnov
13  ACHOA               Praha 4-Chodov

In [20]:
air_quality_data = downloader.download_airquality_data()

air_quality_data.head()

Loaded 14 station IDs from air_stat_dict.csv for filtering.
Found 8753 hourly air-quality files.
Request failed for airquality_1h_avg_CZ_2025022009.csv: HTTPSConnectionPool(host='opendata.chmi.cz', port=443): Max retries exceeded with url: /air_quality/recent/data/airquality_1h_avg_CZ_2025022009.csv (Caused by ConnectTimeoutError(<HTTPSConnection(host='opendata.chmi.cz', port=443) at 0x27cfbfe0cd0>, 'Connection to opendata.chmi.cz timed out. (connect timeout=60)'))
Request failed for airquality_1h_avg_CZ_2025022413.csv: HTTPSConnectionPool(host='opendata.chmi.cz', port=443): Max retries exceeded with url: /air_quality/recent/data/airquality_1h_avg_CZ_2025022413.csv (Caused by ConnectTimeoutError(<HTTPSConnection(host='opendata.chmi.cz', port=443) at 0x27cfbfe0e10>, 'Connection to opendata.chmi.cz timed out. (connect timeout=60)'))
Request failed for airquality_1h_avg_CZ_2025030610.csv: HTTPSConnectionPool(host='opendata.chmi.cz', port=443): Max retries exceeded with url: /air_quality/recent/data/airquality_1h_avg_CZ_2025030610.csv (Caused by ConnectTimeoutError(<HTTPSConnection(host='opendata.chmi.cz', port=443) at 0x27cfbfe0f50>, 'Connection to opendata.chmi.cz timed out. (connect timeout=60)'))
Request failed for airquality_1h_avg_CZ_2025031305.csv: HTTPSConnectionPool(host='opendata.chmi.cz', port=443): Max retries exceeded with url: /air_quality/recent/data/airquality_1h_avg_CZ_2025031305.csv (Caused by ConnectTimeoutError(<HTTPSConnection(host='opendata.chmi.cz', port=443) at 0x27cfbfe0e10>, 'Connection to opendata.chmi.cz timed out. (connect timeout=60)'))
Request failed for airquality_1h_avg_CZ_2025031306.csv: HTTPSConnectionPool(host='opendata.chmi.cz', port=443): Max retries exceeded with url: /air_quality/recent/data/airquality_1h_avg_CZ_2025031306.csv (Caused by ConnectTimeoutError(<HTTPSConnection(host='opendata.chmi.cz', port=443) at 0x27cfbfe11d0>, 'Connection to opendata.chmi.cz timed out. (connect timeout=60)'))
Request failed for airquality_1h_avg_CZ_2025031307.csv: HTTPSConnectionPool(host='opendata.chmi.cz', port=443): Max retries exceeded with url: /air_quality/recent/data/airquality_1h_avg_CZ_2025031307.csv (Caused by ConnectTimeoutError(<HTTPSConnection(host='opendata.chmi.cz', port=443) at 0x27cfbfe1450>, 'Connection to opendata.chmi.cz timed out. (connect timeout=60)'))
Request failed for airquality_1h_avg_CZ_2025042323.csv: HTTPSConnectionPool(host='opendata.chmi.cz', port=443): Max retries exceeded with url: /air_quality/recent/data/airquality_1h_avg_CZ_2025042323.csv (Caused by ConnectTimeoutError(<HTTPSConnection(host='opendata.chmi.cz', port=443) at 0x27cfbfe0cd0>, 'Connection to opendata.chmi.cz timed out. (connect timeout=60)'))
Request failed for airquality_1h_avg_CZ_2025052819.csv: HTTPSConnectionPool(host='opendata.chmi.cz', port=443): Max retries exceeded with url: /air_quality/recent/data/airquality_1h_avg_CZ_2025052819.csv (Caused by ConnectTimeoutError(<HTTPSConnection(host='opendata.chmi.cz', port=443) at 0x27cfbfe16d0>, 'Connection to opendata.chmi.cz timed out. (connect timeout=60)'))
Request failed for airquality_1h_avg_CZ_2025070314.csv: HTTPSConnectionPool(host='opendata.chmi.cz', port=443): Max retries exceeded with url: /air_quality/recent/data/airquality_1h_avg_CZ_2025070314.csv (Caused by ConnectTimeoutError(<HTTPSConnection(host='opendata.chmi.cz', port=443) at 0x27cfbfe1450>, 'Connection to opendata.chmi.cz timed out. (connect timeout=60)'))
Request failed for airquality_1h_avg_CZ_2025071410.csv: HTTPSConnectionPool(host='opendata.chmi.cz', port=443): Max retries exceeded with url: /air_quality/recent/data/airquality_1h_avg_CZ_2025071410.csv (Caused by ConnectTimeoutError(<HTTPSConnection(host='opendata.chmi.cz', port=443) at 0x27cfbfe0cd0>, 'Connection to opendata.chmi.cz timed out. (connect timeout=60)'))
Request failed for airquality_1h_avg_CZ_2025080416.csv: HTTPSConnectionPool(host='opendata.chmi.cz', port=443): Max retries exceeded with url: /air_quality/recent/data/airquality_1h_avg_CZ_2025080416.csv (Caused by ConnectTimeoutError(<HTTPSConnection(host='opendata.chmi.cz', port=443) at 0x27cfbfe11d0>, 'Connection to opendata.chmi.cz timed out. (connect timeout=60)'))
Request failed for airquality_1h_avg_CZ_2025090705.csv: HTTPSConnectionPool(host='opendata.chmi.cz', port=443): Max retries exceeded with url: /air_quality/recent/data/airquality_1h_avg_CZ_2025090705.csv (Caused by ConnectTimeoutError(<HTTPSConnection(host='opendata.chmi.cz', port=443) at 0x27cfbfe0f50>, 'Connection to opendata.chmi.cz timed out. (connect timeout=60)'))
Request failed for airquality_1h_avg_CZ_2025091304.csv: HTTPSConnectionPool(host='opendata.chmi.cz', port=443): Max retries exceeded with url: /air_quality/recent/data/airquality_1h_avg_CZ_2025091304.csv (Caused by ConnectTimeoutError(<HTTPSConnection(host='opendata.chmi.cz', port=443) at 0x27cfbfe0e10>, 'Connection to opendata.chmi.cz timed out. (connect timeout=60)'))
Request failed for airquality_1h_avg_CZ_2025091305.csv: HTTPSConnectionPool(host='opendata.chmi.cz', port=443): Max retries exceeded with url: /air_quality/recent/data/airquality_1h_avg_CZ_2025091305.csv (Caused by ConnectTimeoutError(<HTTPSConnection(host='opendata.chmi.cz', port=443) at 0x27cfbfe1bd0>, 'Connection to opendata.chmi.cz timed out. (connect timeout=60)'))
Request failed for airquality_1h_avg_CZ_2025091502.csv: HTTPSConnectionPool(host='opendata.chmi.cz', port=443): Max retries exceeded with url: /air_quality/recent/data/airquality_1h_avg_CZ_2025091502.csv (Caused by ConnectTimeoutError(<HTTPSConnection(host='opendata.chmi.cz', port=443) at 0x27cfbfe1e50>, 'Connection to opendata.chmi.cz timed out. (connect timeout=60)'))
Request failed for airquality_1h_avg_CZ_2025091503.csv: HTTPSConnectionPool(host='opendata.chmi.cz', port=443): Max retries exceeded with url: /air_quality/recent/data/airquality_1h_avg_CZ_2025091503.csv (Caused by ConnectTimeoutError(<HTTPSConnection(host='opendata.chmi.cz', port=443) at 0x27cfbfe2210>, 'Connection to opendata.chmi.cz timed out. (connect timeout=60)'))
Request failed for airquality_1h_avg_CZ_2025091504.csv: HTTPSConnectionPool(host='opendata.chmi.cz', port=443): Max retries exceeded with url: /air_quality/recent/data/airquality_1h_avg_CZ_2025091504.csv (Caused by ConnectTimeoutError(<HTTPSConnection(host='opendata.chmi.cz', port=443) at 0x27cfbfe2490>, 'Connection to opendata.chmi.cz timed out. (connect timeout=60)'))
Request failed for airquality_1h_avg_CZ_2025112120.csv: HTTPSConnectionPool(host='opendata.chmi.cz', port=443): Max retries exceeded with url: /air_quality/recent/data/airquality_1h_avg_CZ_2025112120.csv (Caused by ConnectTimeoutError(<HTTPSConnection(host='opendata.chmi.cz', port=443) at 0x27cfbfe2710>, 'Connection to opendata.chmi.cz timed out. (connect timeout=60)'))
Request failed for airquality_1h_avg_CZ_2025122618.csv: HTTPSConnectionPool(host='opendata.chmi.cz', port=443): Max retries exceeded with url: /air_quality/recent/data/airquality_1h_avg_CZ_2025122618.csv (Caused by ConnectTimeoutError(<HTTPSConnection(host='opendata.chmi.cz', port=443) at 0x27cfbfe1950>, 'Connection to opendata.chmi.cz timed out. (connect timeout=60)'))

Empty DataFrame
Columns: []
Index: []

In [ ]:
# data processing