In [11]:
import os, sys
import pandas as pd 
import numpy as np

from dotenv import load_dotenv

import requests 
import json 

from bs4 import BeautifulSoup
import io

import csv

import time

In [10]:
libs = [pd, requests]

for lib in libs:
    print(f"{lib.__name__}=={lib.__version__}")

pandas==3.0.0
requests==2.33.0

In [12]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent   # notebooks/ -> project root
sys.path.insert(0, str(PROJECT_ROOT))
RAW_DIR = PROJECT_ROOT / "data" / "raw"

In [13]:
### import funcctions from .py to download the data
from src.download_data import (
    download_airquality_metadata,
    download_airquality_data,
    get_chmi_weather_stations_metadata,
    get_chmi_weather_variables_metadata,
    get_chmi_weather_data
)

In [14]:
# chmi metadata

get_chmi_weather_stations_metadata()
get_chmi_weather_variables_metadata()

,OBS_TYPE,WSI,BEGIN_DATE,END_DATE,EG_EL_ABBREVIATION,NAME,UN_DESCRIPTION,HEIGHT,SCHEDULE
0,DLY,0-20000-0-11406,1865-06-01T00:00:00Z,1919-12-31T23:59:00Z,TMA,Teplota max,°C,2.0,20:00
1,DLY,0-20000-0-11406,1865-06-01T00:00:00Z,1919-12-31T23:59:00Z,TMI,Teplota min,°C,2.0,20:00
2,DLY,0-20000-0-11406,1863-10-01T00:00:00Z,1919-12-31T23:59:00Z,T,Teplota,°C,2.0,"06:00,13:00,20:00,AVG"
3,DLY,0-20000-0-11406,1933-05-07T00:00:00Z,1938-04-30T23:59:00Z,SSV,Sluneční svit,hod,2.0,00:00
4,DLY,0-20000-0-11406,1943-06-01T00:00:00Z,1945-01-31T23:59:00Z,SSV,Sluneční svit,hod,2.0,00:00
...,...,...,...,...,...,...,...,...,...
80483,10M,0-203-0-42108066001,2018-02-09T00:00:00Z,3999-12-31T23:59:00Z,SRA10M,Srážka-10M,mm,1.0,10M
80484,10M,0-203-0-42109005003,2015-09-16T00:00:00Z,3999-12-31T23:59:00Z,H,Vlhkost relat,%,2.0,10M
80485,10M,0-203-0-42109005003,2015-09-16T00:00:00Z,3999-12-31T23:59:00Z,SVHa,Vodní hodnota,mm,0.0,10M
80486,10M,0-203-0-42109005003,2015-09-16T00:00:00Z,3999-12-31T23:59:00Z,SCEa,Výška sněhu,cm,0.0,10M
80487,10M,0-203-0-42109005003,2015-09-16T00:00:00Z,3999-12-31T23:59:00Z,T,Teplota,°C,2.0,10M

In [15]:
# CHMI data

get_chmi_weather_data()

,STATION,ELEMENT,DT,VAL,FLAG,QUALITY,WSI,YEAR,MONTH
0,0-203-0-10904013001,H,2025-01-01T00:00:00Z,93.0,,0.0,0-203-0-10904013001,2025,01
1,0-203-0-10904013001,H,2025-01-01T00:10:00Z,93.0,,0.0,0-203-0-10904013001,2025,01
2,0-203-0-10904013001,H,2025-01-01T00:20:00Z,93.0,,0.0,0-203-0-10904013001,2025,01
3,0-203-0-10904013001,H,2025-01-01T00:30:00Z,93.0,,0.0,0-203-0-10904013001,2025,01
4,0-203-0-10904013001,H,2025-01-01T00:40:00Z,93.0,,0.0,0-203-0-10904013001,2025,01
...,...,...,...,...,...,...,...,...,...
5045395,0-203-0-11101007001,T,2025-12-31T23:10:00Z,-3.7,,0.0,0-203-0-11101007001,2025,12
5045396,0-203-0-11101007001,T,2025-12-31T23:20:00Z,-3.6,,0.0,0-203-0-11101007001,2025,12
5045397,0-203-0-11101007001,T,2025-12-31T23:30:00Z,-3.6,,0.0,0-203-0-11101007001,2025,12
5045398,0-203-0-11101007001,T,2025-12-31T23:40:00Z,-3.6,,0.0,0-203-0-11101007001,2025,12
5045399,0-203-0-11101007001,T,2025-12-31T23:50:00Z,-3.5,,0.0,0-203-0-11101007001,2025,12

In [16]:
# CHMI air-quality files

download_airquality_metadata()

,id_registration,station_code,locality_code,locality_name,street,city,lon,lat,alt,component_code,component_name,unit
0,40555,TOFFA,TOFF,Ostrava-Fifejdy,Gen. Janouška,Ostrava - Fifejdy,18.263689,49.839188,220 m,SO2,oxid siřičitý,ug/m^3
1,40557,TOFFA,TOFF,Ostrava-Fifejdy,Gen. Janouška,Ostrava - Fifejdy,18.263689,49.839188,220 m,NO2,oxid dusičitý,ug/m^3
2,40560,TOFFA,TOFF,Ostrava-Fifejdy,Gen. Janouška,Ostrava - Fifejdy,18.263689,49.839188,220 m,NOx,oxidy dusíku,ug/m^3
3,40559,TOFFA,TOFF,Ostrava-Fifejdy,Gen. Janouška,Ostrava - Fifejdy,18.263689,49.839188,220 m,O3,přízemní ozon,ug/m^3
4,40561,TOFFA,TOFF,Ostrava-Fifejdy,Gen. Janouška,Ostrava - Fifejdy,18.263689,49.839188,220 m,PM10,částice PM10,ug/m^3
...,...,...,...,...,...,...,...,...,...,...,...,...
479,1648406,TRYCA,TRYC,Rychvald,Mírová,Rychvald,18.377254,49.871670,241 m,INDX,Index kvality ovzduší,
480,1410468,ACHOA,ACHO,Praha 4-Chodov,Vejvanovského,Praha 4,14.517450,50.030170,300 m,NO2,oxid dusičitý,ug/m^3
481,1410474,ACHOA,ACHO,Praha 4-Chodov,Vejvanovského,Praha 4,14.517450,50.030170,300 m,NOx,oxidy dusíku,ug/m^3
482,1410479,ACHOA,ACHO,Praha 4-Chodov,Vejvanovského,Praha 4,14.517450,50.030170,300 m,PM10,částice PM10,ug/m^3
483,1648733,ACHOA,ACHO,Praha 4-Chodov,Vejvanovského,Praha 4,14.517450,50.030170,300 m,INDX,Index kvality ovzduší,

In [17]:
download_airquality_data()

Downloading raw data from: airquality_1h_avg_CZ_2026050615.csv

     idRegistration              startTime   idValueType   value
0             10221   2026-05-06T15:00:00Z             8     8.3
1             40237   2026-05-06T15:00:00Z             8     4.2
2             40238   2026-05-06T15:00:00Z             8    89.4
3             40244   2026-05-06T15:00:00Z             8    87.6
4             40257   2026-05-06T15:00:00Z             8     5.1
..              ...                    ...           ...     ...
467         2181672   2026-05-06T15:00:00Z             8     7.1
468         2181676   2026-05-06T15:00:00Z             8     4.3
469         2187304   2026-05-06T15:00:00Z             8    27.6
470         2187315   2026-05-06T15:00:00Z             8     6.4
471         2200581   2026-05-06T15:00:00Z             8     4.0

[472 rows x 4 columns]

In [80]:
# utility 
def print_json_structure(obj, indent=0):
    pad = "  " * indent
    if isinstance(obj, dict):
        for key, value in obj.items():
            print(f"{pad}{key}: {type(value).__name__}")
            print_json_structure(value, indent + 1)
    elif isinstance(obj, list):
        print(f"{pad}[list] len={len(obj)}")
        if obj:
            print_json_structure(obj[0], indent + 1)

def print_json_structure_from_url(url):
    obj = requests.get(url).json()
    print_json_structure(obj)

In [ ]:
#data chmi

#https://opendata.chmi.cz/meteorology/climate/historical/data/1hour/

In [81]:
print_json_structure_from_url("https://opendata.chmi.cz/meteorology/climate/historical/metadata/meta1.json")

zaznamID: str
datovyZdrojID: str
datovyTokID: str
datumVytvoreni: str
verzeDat: str
data: dict
  type: str
  data: dict
    header: str
    values: list
      [list] len=5539
        [list] len=8

In [70]:
def get_chmi_weather_stations_metadata(out_path: Path|str = RAW_DIR / "chmi_weather_stations_metadata.csv"):
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    url = "https://opendata.chmi.cz/"
    route = "/meteorology/climate/historical/metadata/meta1.json"
    headers = {
        "accept": "application/json",
        "User-Agent": "JEM207 DataProcessingCourse (Educational access; contact: 19658413@fsv.cuni.cz)",
    }
    resp = requests.get(f"{url}{route}", headers=headers, timeout=60)
    resp.raise_for_status()
    response = resp.json()
    data_response = response.get('data', {}).get('data', {})
    headers = data_response.get('header', '').split(',')
    values = data_response.get('values', [])
    df = pd.DataFrame(values, columns=headers)
    df.to_csv(out_path, index=False, encoding="utf-8-sig")
    return df


chmi_weather_stations = get_chmi_weather_stations_metadata()

In [71]:
chmi_weather_stations.head()

,WSI,GH_ID,BEGIN_DATE,END_DATE,FULL_NAME,GEOGR1,GEOGR2,ELEVATION
0,0-20000-0-04030,ZIS04030,2015-01-01T00:00:00Z,3999-12-31T23:59:00Z,Reykjavik,-21.903905,64.127653,51.0
1,0-20000-0-11406,L3CHEB01,1863-10-01T00:00:00Z,1919-12-31T23:59:00Z,Cheb,12.362892,50.076212,458.0
2,0-20000-0-11406,L3CHEB01,1933-05-07T00:00:00Z,1938-04-30T23:59:00Z,Cheb,12.388900,50.0739,471.0
3,0-20000-0-11406,L3CHEB01,1943-06-01T00:00:00Z,1945-01-31T23:59:00Z,Cheb,12.388900,50.0739,471.0
4,0-20000-0-11406,L3CHEB01,1951-01-01T00:00:00Z,1960-12-31T23:59:00Z,Cheb,12.388900,50.0739,471.0

In [ ]:
### chmi data variables

In [82]:
print_json_structure_from_url("https://opendata.chmi.cz/meteorology/climate/historical/metadata/meta2.json")

zaznamID: str
datovyZdrojID: str
datovyTokID: str
datumVytvoreni: str
verzeDat: str
data: dict
  type: str
  data: dict
    header: str
    values: list
      [list] len=80488
        [list] len=9

In [ ]:
def get_chmi_weather_variables_metadata(out_path: Path|str = RAW_DIR / "chmi_weather_variables_metadata.csv"):
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    url = "https://opendata.chmi.cz/"
    route = "/meteorology/climate/historical/metadata/meta2.json"
    headers = {
        "accept": "application/json",
        "User-Agent": "JEM207 DataProcessingCourse (Educational access; contact: 19658413@fsv.cuni.cz)",
    }
    resp = requests.get(f"{url}{route}", headers=headers, timeout=60)
    resp.raise_for_status()
    response = resp.json()
    data_response = response.get('data', {}).get('data', {})
    headers = data_response.get('header', '').split(',')
    values = data_response.get('values', [])
    df = pd.DataFrame(values, columns=headers)
    df.to_csv(out_path, index=False, encoding="utf-8-sig")
    return df

df_chmi_vars = get_chmi_weather_variables_metadata()

In [ ]:
df_chmi_vars.head()

In [ ]:
### golemio data 


##### air quality stations 

## metadata: https://opendata.chmi.cz//air_quality/recent/metadata/metadata.json

In [ ]:
def set_api_key(token = 'api_key.env'):
    load_dotenv(token)
    api_key = os.getenv('GOLEMIO_API_KEY')
    if api_key:
        print("API key loaded")
    else:
        print("API key not found")
    return api_key

api_key = set_api_key()

✓ API key loaded

In [ ]:
# def get_airquality_stations_metadata():
#     url = 'https://api.golemio.cz/'
#     route = '/v2/airqualitystations'

#     headers = {
#         'X-access-token': api_key, 
#         'accept': 'application/json',
#         'User-Agent': 'JEM207 DataProcessingCourse (Educational access; contact: 19658413@fsv.cuni.cz)'
#     }

#     response = requests.get(f'{url}{route}', headers = headers, timeout = 60)
#     response.raise_for_status()

#     data = response.json()
#     df = pd.json_normalize(data.get('features', {}))

#     tmp = df.explode("properties.measurement.components", ignore_index=True)
#     dirs = pd.json_normalize(
#         tmp["properties.measurement.components"]
#     ).add_prefix("properties.measurement.components.")

#     df = pd.concat([tmp.drop(columns=["properties.measurement.components"]), dirs], axis=1)

#     df.to_csv("data/airquality_stations_metadata.csv", index=False, encoding="utf-8-sig")

# get_airquality_stations_metadata()

In [ ]:
### chmi weather data

# 10 min data download

In [ ]:
print_json_structure_from_url("https://opendata.chmi.cz/meteorology/climate/historical/data/10min/2025/10m-0-203-0-11514-202511.json")

zaznamID: str
datovyZdrojID: str
datovyTokID: str
datumVytvoreni: str
verzeDat: str
data: dict
  type: str
  data: dict
    header: str
    values: list
      [list] len=62490
        [list] len=6

In [88]:
def get_chmi_weather_data(start_year=2025, end_year=2025, wsi_csv = RAW_DIR / "wsi_dict.csv", out_path: Path|str = RAW_DIR / "weather_data_10min.csv"):
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    base_url = "https://opendata.chmi.cz/"
    route_template = "/meteorology/climate/historical/data/10min/{year}/10m-{wsi}-{ym}.json"
    url_header = {
        "accept": "application/json",
        "User-Agent": "JEM207 DataProcessingCourse (Educational access; contact: 19658413@fsv.cuni.cz)",
    }
    # we set to dowload only data from selected stations to not get unnecessary big dataset
    wsi_dict = pd.read_csv(wsi_csv, encoding="utf-8-sig").set_index("key")["value"].to_dict()
    years = [f"{y}" for y in range(start_year, end_year + 1)]
    months = [11] #[f"{m:02d}" for m in range(1, 13)]
    results = []
    for wsi in wsi_dict:
        for year in years:
            for month in months:
                ym = f"{year}{month}"
                route = route_template.format(year=year, wsi=wsi, ym=ym)
                try:
                    time.sleep(0.5)
                    response = requests.get(f"{base_url}{route}", headers=url_header, timeout=90)
                    response.raise_for_status()
                except requests.exceptions.RequestException as exc:
                    print(f"Request failed for {wsi} {wsi_dict.get(wsi)} {year} {month}: {exc}")
                    continue
                response = response.json()
                data_response = response.get("data", {}).get("data", {})
                headers = data_response.get("header", "").split(",")
                values = data_response.get("values", [])
                if not values:
                    continue
                df_part = pd.DataFrame(values, columns=headers)
                df_part["WSI"] = wsi
                df_part["YEAR"] = year
                df_part["MONTH"] = month
                results.append(df_part)
    if not results:
        return pd.DataFrame()
    df = pd.concat(results, ignore_index=True)
    df.to_csv(out_path, index=False, encoding="utf-8-sig")
    return df
    
df_weather = get_chmi_weather_data()

In [89]:
df_weather.head()

,STATION,ELEMENT,DT,VAL,FLAG,QUALITY,WSI,YEAR,MONTH
0,0-203-0-10904013001,H,2025-11-01T00:00:00Z,96.0,,0.0,0-203-0-10904013001,2025,11
1,0-203-0-10904013001,H,2025-11-01T00:10:00Z,95.0,,0.0,0-203-0-10904013001,2025,11
2,0-203-0-10904013001,H,2025-11-01T00:20:00Z,96.0,,0.0,0-203-0-10904013001,2025,11
3,0-203-0-10904013001,H,2025-11-01T00:30:00Z,96.0,,0.0,0-203-0-10904013001,2025,11
4,0-203-0-10904013001,H,2025-11-01T00:40:00Z,96.0,,0.0,0-203-0-10904013001,2025,11

In [ ]:
### weather data for 1hour -- if needed

# base_url = "https://opendata.chmi.cz/"
# route_template = "/meteorology/climate/historical/data/1hour/{year}/1h-{wsi}-{ym}.json"

# url_header = {
#     'accept': 'application/json',
#     'User-Agent': 'JEM207 DataProcessingCourse (Educational access; contact: 19658413@fsv.cuni.cz)'
# }

# years = [2025]
# months = [11] #[f"{m:02d}" for m in range(1, 13)]

# results = []

# for wsi in wsi_dict:
#     for year in years:
#         for month in months:
#             ym = f"{year}{month}"
#             route = route_template.format(year=year, wsi=wsi, ym=ym)

#             try:
#                 response = requests.get(f"{base_url}{route}", headers=url_header, timeout=60)
#                 response.raise_for_status()
#             except requests.exceptions.RequestException as exc:
#                 print(f"Request failed for {wsi} {wsi_dict.get(wsi)} {year} {month}: {exc}")
#                 continue

#             data_response = response.json()
#             data_response = data_response['data']['data']

#             headers = data_response['header'].split(',')
#             values = data_response['values']

#             df_part = pd.DataFrame(values, columns=headers)
#             df_part["WSI"] = wsi
#             df_part["YEAR"] = year
#             df_part["MONTH"] = month

#             results.append(df_part)




# df_chmi = pd.concat(results, ignore_index=True)

Failed for 0-203-0-11515 Praha, Klementinum 2025 11: 404
Failed for 0-203-0-11105048001 Praha, Zadní Kopanina 2025 11: 404
Failed for 0-203-0-11101007001 Praha, Brdy 2025 11: 404
Failed for 0-203-0-11202007001 Praha, Suchdol 2025 11: 404
Failed for 0-203-0-11201020003 Praha, Chodov 2025 11: 404

In [ ]:
### golemio 

### air quality data

In [ ]:
# api_url = 'https://api.golemio.cz/'
# route = '/v2/airqualitystations/history'

# headers = {
#     'X-access-token': api_key, 
#     'accept': 'application/json',
#     'User-Agent': 'JEM207 DataProcessingCourse (Educational access; contact: 19658413@fsv.cuni.cz)'
# }

# params = {
#     'from': '2024-05-16T04:27:58.000Z', 
#     'to': '2024-06-18T04:27:58.000Z'
# }

# response = requests.get(f'{api_url}{route}', headers=headers, params=params, timeout=60)

# data = response.json()

In [ ]:
# print(json.dumps(data, indent=2))

{
  "error_message": "Not Found",
  "error_status": 404
}

In [ ]:
# if data:
#     print("Top level keys:", data[0].keys())
#     print("Measurement level keys:", data[0]['measurement'].keys())

Top level keys: dict_keys(['id', 'measurement'])
Measurement level keys: dict_keys(['AQ_hourly_index', 'components'])

In [ ]:
# df = pd.json_normalize(
#     data,
#     record_path=["measurement", "components"],
#     meta=[
#         "id",
#         ["measurement", "AQ_hourly_index"],
#     ],
#     sep=".",
#     errors="raise",
# )

In [ ]:
# TODO add a script to read one .csv file and display head

In [ ]:
#### aternative air quality - chmi air quality

def download_airquality_data(data_dir_url="https://opendata.chmi.cz/air_quality/recent/data/", out_path: Path|str = RAW_DIR / "airquality_CHMI_stations_data.csv"):
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    resp = requests.get(data_dir_url, timeout=60)
    resp.raise_for_status()
    soup = BeautifulSoup(resp.text, "html.parser")
    csv_files = [link.get("href") for link in soup.find_all("a") if link.get("href", "").endswith(".csv")]
    if not csv_files:
        raise FileNotFoundError("No CSV files found in the directory.")
    latest_file = sorted(csv_files)[-1]
    file_url = f"{data_dir_url}{latest_file}"
    print(f"Downloading raw data from: {latest_file}")
    data_response = requests.get(file_url)
    data_response.raise_for_status()
    df_data = pd.read_csv(io.StringIO(data_response.text))
    df_data.to_csv(out_path, index=False, encoding="utf-8-sig")
    return df_data

df_air_qual = download_air_quality_data()

Downloading raw data from: airquality_1h_avg_CZ_2026050113.csv

In [91]:
df_air_qual.head()

   idRegistration              startTime   idValueType   value
0           10221   2026-05-01T13:00:00Z             8     2.9
1           40237   2026-05-01T13:00:00Z             8     3.2
2           40238   2026-05-01T13:00:00Z             8   111.5
3           40244   2026-05-01T13:00:00Z             8   106.1
4           40257   2026-05-01T13:00:00Z             8     1.3

In [ ]:
def download_airquality_metadata(metadata_url="https://opendata.chmi.cz/air_quality/recent/metadata/metadata.json", out_path: Path|str = RAW_DIR / "airquality_CHMI_stations_metadata.csv"):
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    resp = requests.get(metadata_url, timeout=60)
    resp.raise_for_status()
    metadata = resp.json()
    mapping_list = []
    localities = metadata.get("data", {}).get("Localities", [])
    for locality in localities:
        loc_code = locality.get("LocalityCode", {})
        loc_name = locality.get("Name", {})
        loc = locality.get("Localization", {})
        lon = loc.get("LonAsNumber")
        lat = loc.get("LatAsNumber")
        alt = loc.get("Alt")
        addr = locality.get("Address", {})
        street = addr.get("Street")
        city = addr.get("City")
        programs = locality.get("MeasuringPrograms", [])
        for program in programs:
            station_code = program.get("Code")
            measurements = program.get("Measurements", [])
            for measurement in measurements:
                row = {
                    "id_registration": measurement.get("IdRegistration"),
                    "station_code": station_code,
                    "locality_code": loc_code,
                    "locality_name": loc_name,
                    "street": street,
                    "city": city,
                    "lon": lon,
                    "lat": lat,
                    "alt": alt,
                    "component_code": measurement.get("ComponentCode"),
                    "component_name": measurement.get("ComponentName"),
                    "unit": measurement.get("UnitAsASCII"),
                }
                mapping_list.append(row)
    df_mapping = pd.DataFrame(mapping_list)
    df_mapping.to_csv(out_path, index=False, encoding="utf-8-sig")
    return df_mapping

air_qual_meta = download_air_quality_metadata()

In [94]:
air_qual_meta.head()

,id_registration,station_code,locality_code,locality_name,street,city,lon,lat,alt,component_code,component_name,unit
0,40555,TOFFA,TOFF,Ostrava-Fifejdy,Gen. Janouška,Ostrava - Fifejdy,18.263689,49.839188,220 m,SO2,oxid siřičitý,ug/m^3
1,40557,TOFFA,TOFF,Ostrava-Fifejdy,Gen. Janouška,Ostrava - Fifejdy,18.263689,49.839188,220 m,NO2,oxid dusičitý,ug/m^3
2,40560,TOFFA,TOFF,Ostrava-Fifejdy,Gen. Janouška,Ostrava - Fifejdy,18.263689,49.839188,220 m,NOx,oxidy dusíku,ug/m^3
3,40559,TOFFA,TOFF,Ostrava-Fifejdy,Gen. Janouška,Ostrava - Fifejdy,18.263689,49.839188,220 m,O3,přízemní ozon,ug/m^3
4,40561,TOFFA,TOFF,Ostrava-Fifejdy,Gen. Janouška,Ostrava - Fifejdy,18.263689,49.839188,220 m,PM10,částice PM10,ug/m^3

In [ ]:
air_qual_meta = air_qual_meta[air_qual_meta['locality_name'].str.contains('Praha', case=False, na=False)]

In [18]:
#### golemio

### microclimate sensors

In [19]:
# TODO if necessary